import type { Product } from "./types"

const img = (q: string, w = 800, h = 800) => `/placeholder.svg?height=${h}&width=${w}&query=${encodeURIComponent(q)}`

export const PRODUCTS: Product[] = [
  // Existing Sunglasses
  {
    id: "sg-men-001",
    name: "Aether Classic Aviator",
    category: "sunglasses",
    gender: "men",
    material: "titanium",
    color: "gunmetal",
    shape: "aviator",
    price: 299,
    salePrice: 239,
    images: [img("aether aviator front"), img("aether aviator side")],
    rating: 4.7,
  },
  
  {
    id: "sg-women-002",
    name: "Lumen Cat-Eye",
    category: "sunglasses",
    gender: "women",
    material: "acetate",
    color: "onyx",
    shape: "cat-eye",
    price: 249,
    images: [img("lumen cat eye front"), img("lumen cat eye detail")],
    rating: 4.6,
  },
  {
    id: "sg-unx-003",
    name: "Axis Square",
    category: "sunglasses",
    gender: "unisex",
    material: "metal",
    color: "brushed gold",
    shape: "square",
    price: 219,
    salePrice: 179,
    images: [img("axis square front"), img("axis square side")],
  },
  // New Sunglasses
  {
    id: "sg-men-004",
    name: "Vortex Shield",
    category: "sunglasses",
    gender: "men",
    material: "metal",
    color: "matte black",
    shape: "aviator",
    price: 279,
    salePrice: 229,
    images: [img("vortex shield front"), img("vortex shield side")],
  },
  {
    id: "sg-women-005",
    name: "Aurora Round",
    category: "sunglasses",
    gender: "women",
    material: "acetate",
    color: "rose gold",
    shape: "round",
    price: 259,
    images: [img("aurora round front"), img("aurora round detail")],
  },
  {
    id: "sg-unx-006",
    name: "Zenith Wrap",
    category: "sunglasses",
    gender: "unisex",
    material: "metal",
    color: "gunmetal gray",
    shape: "aviator",
    price: 299,
    salePrice: 249,
    images: [img("zenith wrap front"), img("zenith wrap side")],
  },

  // Existing Optics
  {
    id: "op-men-101",
    name: "Vector Pro",
    category: "optics",
    gender: "men",
    material: "titanium",
    color: "graphite",
    shape: "rectangular",
    price: 279,
    images: [img("vector pro front"), img("vector pro hinge")],
  },
  {
    id: "op-women-102",
    name: "Aura Light",
    category: "optics",
    gender: "women",
    material: "acetate",
    color: "crystal",
    shape: "oval",
    price: 239,
    salePrice: 199,
    images: [img("aura light front"), img("aura light detail")],
  },
  {
    id: "op-unx-103",
    name: "Forma Neutral",
    category: "optics",
    gender: "unisex",
    material: "mixed",
    color: "sand",
    shape: "round",
    price: 209,
    images: [img("forma neutral front"), img("forma neutral side")],
  },
  // New Optics
  {
    id: "op-men-104",
    name: "Clarity Edge",
    category: "optics",
    gender: "men",
    material: "titanium",
    color: "black matte",
    shape: "rectangular",
    price: 269,
    images: [img("clarity edge front"), img("clarity edge side")],
  },
  {
    id: "op-women-105",
    name: "Lumiere Oval",
    category: "optics",
    gender: "women",
    material: "acetate",
    color: "pearl white",
    shape: "oval",
    price: 249,
    salePrice: 209,
    images: [img("lumiere oval front"), img("lumiere oval detail")],
  },
  {
    id: "op-unx-106",
    name: "Horizon Round",
    category: "optics",
    gender: "unisex",
    material: "mixed",
    color: "taupe",
    shape: "round",
    price: 229,
    images: [img("horizon round front"), img("horizon round side")],
  },

  {
  id: "op-kids-001",
  name: "Mini Vector",
  category: "optics",
  gender: "kids",
  material: "titanium",
  color: "blue",
  shape: "rectangular",
  price: 149,
  salePrice: 129,
  images: [img("mini vector front"), img("mini vector side")],
  rating: 4.5,
},
{
  id: "op-kids-002",
  name: "Tiny Aura",
  category: "optics",
  gender: "kids",
  material: "acetate",
  color: "pink",
  shape: "round",
  price: 139,
  salePrice: 119,
  images: [img("tiny aura front"), img("tiny aura side")],
  rating: 4.4,
},
{
  id: "op-kids-003",
  name: "Junior Forma",
  category: "optics",
  gender: "kids",
  material: "mixed",
  color: "green",
  shape: "oval",
  price: 159,
  images: [img("junior forma front"), img("junior forma side")],
  rating: 4.6,
},
{
  id: "op-kids-004",
  name: "Little Prism",
  category: "optics",
  gender: "kids",
  material: "plastic",
  color: "red",
  shape: "square",
  price: 129,
  salePrice: 109,
  images: [img("little prism front"), img("little prism side")],
  rating: 4.3,
},
{
  id: "op-kids-005",
  name: "Kiddo Spectrum",
  category: "optics",
  gender: "kids",
  material: "acetate",
  color: "yellow",
  shape: "rectangular",
  price: 149,
  images: [img("kiddo spectrum front"), img("kiddo spectrum side")],
  rating: 4.2,
},
{
  id: "op-kids-006",
  name: "Tiny Focus",
  category: "optics",
  gender: "kids",
  material: "titanium",
  color: "purple",
  shape: "round",
  price: 159,
  salePrice: 139,
  images: [img("tiny focus front"), img("tiny focus side")],
  rating: 4.5,
},
]
